-- MySQL Script generated by MySQL Workbench
-- Mon Feb  5 12:55:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cadastro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cadastro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cadastro` DEFAULT CHARACTER SET utf8 ;
USE `cadastro` ;

-- -----------------------------------------------------
-- Table `cadastro`.`pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastro`.`pessoas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `nascimento` VARCHAR(45) NULL,
  `cargo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cadastro`.`projetos`pessoaspessoas
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadastro`.`projetos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(445) NULL,
  `dono_id` INT NOT NULL,
  `gerente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dono_inx` (`dono_id` ASC),
  INDEX `fk_gerente_inx` (`gerente_id` ASC),
  CONSTRAINT `fk_dono`
    FOREIGN KEY (`dono_id`)
    REFERENCES `cadastro`.`pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gerente`
    FOREIGN KEY (`gerente_id`)
    REFERENCES `cadastro`.`pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
